// Concordia Smart Contract ABI
export const CONCORDIA_CONTRACT_ABI = [
  {
    inputs: [
      { name: "_name", type: "string" },
      { name: "_description", type: "string" },
      { name: "_goalAmount", type: "uint256" },
      { name: "_duration", type: "uint256" },
      { name: "_withdrawalDate", type: "uint256" },
      { name: "_dueDay", type: "uint8" },
      { name: "_metadataId", type: "string" },
      { name: "_metadataHash", type: "string" },
    ],
    name: "createGroup",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "groupId", type: "uint256" },
      { name: "nickname", type: "string" },
    ],
    name: "joinGroup",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "contribute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "voteForWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "emergencyWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "groupId", type: "uint256" },
      { name: "newMetadataId", type: "string" },
      { name: "newMetadataHash", type: "string" },
    ],
    name: "updateGroupMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "getGroupDetails",
    outputs: [
      {
        components: [
          { name: "id", type: "uint256" },
          { name: "name", type: "string" },
          { name: "description", type: "string" },
          { name: "goalAmount", type: "uint256" },
          { name: "dueDay", type: "uint256" },
          { name: "duration", type: "uint256" },
          { name: "withdrawalDate", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "isActive", type: "bool" },
          { name: "metadataId", type: "string" },
          { name: "metadataHash", type: "string" },
          { name: "createdAt", type: "uint256" },
          { name: "totalContributions", type: "uint256" },
          { name: "memberCount", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "getGroupMembers",
    outputs: [{ name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "groupId", type: "uint256" },
      { name: "member", type: "address" },
    ],
    name: "getMemberDetails",
    outputs: [
      {
        components: [
          { name: "isMember", type: "bool" },
          { name: "contribution", type: "uint256" },
          { name: "auraPoints", type: "uint256" },
          { name: "hasVoted", type: "bool" },
          { name: "joinedAt", type: "uint256" },
          { name: "nickname", type: "string" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "user", type: "address" }],
    name: "getUserGroups",
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "groupId", type: "uint256" }],
    name: "getGroupBalance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalGroups",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "groupId", type: "uint256" },
      { name: "user", type: "address" },
    ],
    name: "isGroupMember",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "name", type: "string" },
      { indexed: false, name: "goalAmount", type: "uint256" },
      { indexed: false, name: "duration", type: "uint256" },
      { indexed: false, name: "metadataHash", type: "string" },
    ],
    name: "GroupCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: false, name: "ipfsHash", type: "string" },
      { indexed: true, name: "deletedBy", type: "address" },
    ],
    name: "GroupDeleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "MemberJoined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: true, name: "member", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "auraPoints", type: "uint256" },
      { indexed: false, name: "isEarly", type: "bool" },
      { indexed: false, name: "transactionHash", type: "string" },
    ],
    name: "Contributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: false, name: "totalAmount", type: "uint256" },
    ],
    name: "WithdrawalExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "groupId", type: "uint256" },
      { indexed: true, name: "executor", type: "address" },
      { indexed: false, name: "penaltyAmount", type: "uint256" },
    ],
    name: "EmergencyWithdrawal",
    type: "event",
  },
] as const