
[phases.setup]
nixPkgs = ["nodejs_16", "npm", "python3", "gcc", "git"]

[phases.install]
cmds = ["npm cache clean --force", "npm install"]

[phases.build]
cmds = ["npm run build"]
packageManager = "npm"
dependencies = ["node-gyp", "python3", "make", "g++"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
